"""add language to cards and sealed_items

Revision ID: a364870d65b7
Revises: b4c4dcdfcd11
Create Date: 2026-05-23 14:55:23.887003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a364870d65b7'
down_revision = 'b4c4dcdfcd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    with op.batch_alter_table('sealed_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sealed_items', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
