"""add sealed catalog

Revision ID: a4e61f699bd4
Revises: e78036c2d3a0
Create Date: 2026-05-22 20:55:21.283059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e61f699bd4'
down_revision = 'e78036c2d3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sealed_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.String(length=60), nullable=False),
    sa.Column('set_name', sa.String(length=100), nullable=True),
    sa.Column('set_code', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sealed_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sealed_catalog_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sealed_catalog_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sealed_catalog_set_code'), ['set_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sealed_catalog_set_name'), ['set_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sealed_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sealed_catalog_set_name'))
        batch_op.drop_index(batch_op.f('ix_sealed_catalog_set_code'))
        batch_op.drop_index(batch_op.f('ix_sealed_catalog_name'))
        batch_op.drop_index(batch_op.f('ix_sealed_catalog_item_type'))

    op.drop_table('sealed_catalog')
    # ### end Alembic commands ###
