"""add rip_sessions and rip_session_cards tables

Revision ID: a6836fdb71c2
Revises: d3f1a9e4c820
Create Date: 2026-05-23 14:20:12.707453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6836fdb71c2'
down_revision = 'd3f1a9e4c820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rip_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pack_name', sa.String(length=200), nullable=False),
    sa.Column('pack_set_name', sa.String(length=100), nullable=True),
    sa.Column('pack_set_code', sa.String(length=20), nullable=True),
    sa.Column('pack_image_url', sa.String(length=500), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.Column('ripped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rip_session_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('card_number', sa.String(length=20), nullable=True),
    sa.Column('set_name', sa.String(length=100), nullable=True),
    sa.Column('set_code', sa.String(length=20), nullable=True),
    sa.Column('rarity', sa.String(length=60), nullable=True),
    sa.Column('variant', sa.String(length=60), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['rip_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rip_session_cards')
    op.drop_table('rip_sessions')
    # ### end Alembic commands ###
