"""add rip_session_id to cards

Revision ID: b4c4dcdfcd11
Revises: a6836fdb71c2
Create Date: 2026-05-23 14:26:25.760871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c4dcdfcd11'
down_revision = 'a6836fdb71c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rip_session_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cards_rip_session_id'), ['rip_session_id'], unique=False)
        batch_op.create_foreign_key('fk_cards_rip_session_id', 'rip_sessions', ['rip_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cards_rip_session_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cards_rip_session_id'))
        batch_op.drop_column('rip_session_id')

    # ### end Alembic commands ###
