"""add card catalog

Revision ID: f8548b29851f
Revises: 62dd52ec8d55
Create Date: 2026-05-21 22:15:18.063480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8548b29851f'
down_revision = '62dd52ec8d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tcg_id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('card_number', sa.String(length=20), nullable=True),
    sa.Column('set_name', sa.String(length=120), nullable=True),
    sa.Column('set_code', sa.String(length=20), nullable=True),
    sa.Column('era', sa.String(length=30), nullable=True),
    sa.Column('rarity', sa.String(length=60), nullable=True),
    sa.Column('supertype', sa.String(length=30), nullable=True),
    sa.Column('types', sa.String(length=120), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('image_small', sa.String(length=500), nullable=True),
    sa.Column('image_large', sa.String(length=500), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_catalog_card_number'), ['card_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_catalog_era'), ['era'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_catalog_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_catalog_set_code'), ['set_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_catalog_set_name'), ['set_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_catalog_tcg_id'), ['tcg_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_catalog_tcg_id'))
        batch_op.drop_index(batch_op.f('ix_card_catalog_set_name'))
        batch_op.drop_index(batch_op.f('ix_card_catalog_set_code'))
        batch_op.drop_index(batch_op.f('ix_card_catalog_name'))
        batch_op.drop_index(batch_op.f('ix_card_catalog_era'))
        batch_op.drop_index(batch_op.f('ix_card_catalog_card_number'))

    op.drop_table('card_catalog')
    # ### end Alembic commands ###
